main/urls.py
from django.urls import path
from .views import IndexView


app_name = 'main'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # URL for main page
]

squadfree/urls.py
from django.contrib import admin
from django.urls import path, include
from squadfree import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Squadfree Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  <!-- Favicons -->
  <link href={% static "assets/img/favicon.png" %} rel="icon">
  <link href={% static "assets/img/apple-touch-icon.png" %} rel="apple-touch-icon">
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <!-- Vendor CSS Files -->
  <link href={% static "assets/vendor/aos/aos.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/boxicons/css/boxicons.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/glightbox/css/glightbox.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/swiper/swiper-bundle.min.css" %} rel="stylesheet">
  <!-- Template Main CSS File -->
  <link href={% static "assets/css/style.css" %} rel="stylesheet">

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top header-transparent">
        <div class="container d-flex align-items-center justify-content-between position-relative">
            <div class="logo">
                <h1 class="text-light"><a href="{% url 'main:index' %}">{{ app_title|safe }}</a></h1>
            </div>
            
            {% include 'includes/nav.html' %} 
            
        </div>
  </header><!-- End Header -->
  
  {% include 'includes/hero.html' %}
  
  <main id="main">
      {% block content %}
      {% endblock %}
  </main>

  {% include 'includes/footer.html' %}

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  <!-- Vendor JS Files -->
  <script src={% static "assets/vendor/purecounter/purecounter_vanilla.js" %} ></script>
  <script src={% static "assets/vendor/aos/aos.js" %} ></script>
  <script src={% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %} ></script>
  <script src={% static "assets/vendor/glightbox/js/glightbox.min.js" %} ></script>
  <script src={% static "assets/vendor/isotope-layout/isotope.pkgd.min.js" %} ></script>
  <script src={% static "assets/vendor/swiper/swiper-bundle.min.js" %} ></script>
  <script src={% static "assets/vendor/php-email-form/validate.js" %} ></script>
  <!-- Template Main JS File -->
  <script src={% static "assets/js/main.js" %} ></script>
</body>
</html>